### ISSUE TITLE
currentMenu not working 

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [CouscousPHP/Template-ReadTheDocs#7]
I have added the markdown in my configuration,md file as follows
---
currentMenu : configuration
---
and  in in my couscous.yml file menus are like as follows 

```
menu:
    items:
        getting-started:
            text: Get started
            relativeUrl: deployment-guide.html
        documentation:
            text: Installation Guide
            relativeUrl: deployment-guide.html
        configuration:
            text: Configuration Guide
            relativeUrl: configuration.html
        troubleshooting:
            text: Troubleshooting
            relativeUrl: troubleshooting.html
        templates:
            text: Release Summary
            relativeUrl: release-summary.html
        faqs:
            text: FAQs
            relativeUrl: faqs.html
        
```

Still i cant set the active menu as i am not getting current_menu in default.twig.
Anyone have solutions or found same issue
